# Converted from JSON to TOML format
name = "login_w_turso"
main = "src/index.ts"
compatibility_date = "2025-01-30"
compatibility_flags = ["nodejs_compat"]

[vars]
USERNAME = "admin"
PASSWORD = "admin"
PLATFORM_DB_URL = "https://uni-login-sukuna.turso.io"
JIRA_DB_URL = "https://uni-login-sukuna.turso.io"
GITLAB_DB_URL = "https://uni-login-sukuna.turso.io"
JENKINS_DB_URL = "https://uni-login-sukuna.turso.io"
SONARQUBE_DB_URL = "https://uni-login-sukuna.turso.io"
SONARSCANNER_DB_URL = "https://uni-login-sukuna.turso.io"
SONARCLOUD_DB_URL = "https://uni-login-sukuna.turso.io"
TURSO_DATABASE_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3MzgyNjQ3NDYsImlkIjoiZmY5ZGM3YjctZDJiZC00N2Q0LWE3ZTktODgwMjk3YTgwZTdlIn0.BkPA06Zu2SdVluIv3QDfXqnEpOMALMbHRH1Wlgs3IMH-Fym04XNRv5_StT1n4e2awQBHJnXDs6WUcOucthyaDg"

# [kv_namespaces]
#   [[kv_namespaces]]
#   binding = "MY_KV_NAMESPACE"
#   id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [r2_buckets]
#   [[r2_buckets]]
#   binding = "MY_BUCKET"
#   bucket_name = "my-bucket"

# [d1_databases]
#   [[d1_databases]]
#   binding = "MY_DB"
#   database_name = "my-database"
#   database_id = ""

# [ai]
#   binding = "AI"

# [observability]
#   enabled = true
#   head_sampling_rate = 1